dubbo:    registry:    address: spring-cloud://localhost  cloud:    subscribed-services: datasource-provider           application:    qos:      port: 22220  protocol:    port: 20882  server:  port: 9082
spring:
  application:
    name: user-service
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false  main:    allow-bean-definition-overriding: truelogging:  level:    com.alibaba.nacos: ERROR